### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by legnaleurc** [tossug/opensource-dashboard#1]
1. 是以 issues 的 search 為主？還是要另外整理一份圖表？
   
   e.g. 缺人的 community/project 就上 issue, 符合特定格式去 parse?
2. 我忘了 issue owner 不能改 label, 可能要 repo owner 手動幫大家改？

**Comment by czchen** [comment]
這個 project 主要是追蹤台灣使用者常用軟體的狀態，要找人的 project 可以在另一個 repo 弄。

**Comment by legnaleurc** [comment]
了解
